[workspace]
resolver = "2"
members = [
    "boot",
    "kernel",
    "memory",
    "ipc",
    "security",
    "fs-vulturefs",
    "apps-shell",
]

[package]
name = "vulture"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
vulture-kernel = { path = "kernel" }